from abc import abstractmethod, ABC

class IFlowManager(ABC):
    """
    The IFlowManager interface declares the operations that all concrete flow
    managers must implement.

    The IFlowManager interface declares a method for resetting the state for a
    specific user and a method for processing a user query and returning a
    response based on the current state and intent.
    """

    @abstractmethod
    def reset_state(self, user_id):
        """
        Resets the state for a specific user.

        Args:
            user_id (str): The ID of the user.

        Returns:
            None
        """
        pass

    @abstractmethod
    def process_query(self, query, session_id):
        """
        Processes a user query and returns a response based on the current state
        and intent.

        Args:
            query (str): The user query.
            session_id (str): The ID of the session.

        Returns:
            str: The response generated by the chatbot.
        """
        pass